def generate_rsa_report(n, e, c, attack_result, output_path):
    """Generate markdown report for RSA attack.

    Args:
        n, e, c: RSA parameters
        attack_result: dict from run_wiener_attack()
        output_path: path to save report
    """
    lines = []

    lines.append("# RSA Attack Report")
    lines.append("")
    lines.append("## Input Parameters")
    lines.append("")
    lines.append(f"- **n** = {n}")
    lines.append(f"- **e** = {e}")
    lines.append(f"- **c** = {c}")
    lines.append("")

    lines.append("## Attack Results")
    lines.append("")

    if attack_result['success']:
        lines.append("**Status:** SUCCESS")
        lines.append("")
        lines.append("### Attack Tried")
        lines.append("- Wiener")
        lines.append("")
        lines.append("### Recovered d")
        d = attack_result['d']
        d_display = str(d)[:50] + "..." if len(str(d)) > 50 else str(d)
        lines.append(f"`{d_display}`")
        lines.append("")
        lines.append("### Plaintext (integer)")
        lines.append(f"`{attack_result['plaintext_int']}`")
        lines.append("")
        lines.append("### Plaintext (text)")
        pt = attack_result['plaintext']
        if pt:
            # Check for flag
            if 'picoCTF{' in pt or 'flag{' in pt.lower():
                lines.append(f"**Flag found:** `{pt}`")
            else:
                lines.append(f"`{pt}`")
        else:
            lines.append("*Could not convert to text*")
    else:
        lines.append("**Status:** FAILED")
        lines.append("")
        lines.append("### Attack Tried")
        lines.append("- Wiener")
        lines.append("")
        if attack_result.get('error'):
            lines.append("### Error")
            lines.append(f"`{attack_result['error']}`")

    lines.append("")
    lines.append("---")
    lines.append("*Generated by ctf-decode-helper RSA mode*")

    report_content = "\n".join(lines)

    with open(output_path, 'w') as f:
        f.write(report_content)

    return output_path
